version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: backend/Api/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - '.:/frontend/app'
      - '/frontend/app/node_modules'
    ports:
      - '4201:4200'

  # backend:
  #   container_name: backend
  #   build:
  #     context: backend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - '.:/backend/app'
  #     - '/backend/app/node_modules'
  #   ports:
  #     - '8080:8080'
